"""Add advanced analytics tables

Revision ID: 1e56ca806f21
Revises: eefd4d96c540
Create Date: 2026-03-22 18:39:56.948481

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1e56ca806f21'
down_revision: Union[str, Sequence[str], None] = 'eefd4d96c540'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('player_injuries',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('player_name', sa.String(length=255), nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('injury_description', sa.String(length=255), nullable=False),
    sa.Column('expected_return', sa.DateTime(), nullable=True),
    sa.Column('importance', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_player_injuries_player_name'), 'player_injuries', ['player_name'], unique=False)
    op.create_index(op.f('ix_player_injuries_team_name'), 'player_injuries', ['team_name'], unique=False)
    op.create_index('ix_player_injuries_team_status', 'player_injuries', ['team_name', 'status'], unique=False)
    op.create_table('team_stats',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('window_games', sa.Integer(), nullable=False),
    sa.Column('avg_xg_for', sa.Float(), nullable=False),
    sa.Column('avg_xg_against', sa.Float(), nullable=False),
    sa.Column('avg_shots_for', sa.Float(), nullable=False),
    sa.Column('avg_shots_against', sa.Float(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_stats_team_name'), 'team_stats', ['team_name'], unique=False)
    op.create_index('ix_team_stats_team_window', 'team_stats', ['team_name', 'window_games'], unique=True)
    op.create_table('match_advanced',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('home_xg', sa.Float(), nullable=True),
    sa.Column('away_xg', sa.Float(), nullable=True),
    sa.Column('home_xgot', sa.Float(), nullable=True),
    sa.Column('away_xgot', sa.Float(), nullable=True),
    sa.Column('home_shots', sa.Integer(), nullable=True),
    sa.Column('away_shots', sa.Integer(), nullable=True),
    sa.Column('home_possession', sa.Float(), nullable=True),
    sa.Column('away_possession', sa.Float(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_advanced_match_id'), 'match_advanced', ['match_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_advanced_match_id'), table_name='match_advanced')
    op.drop_table('match_advanced')
    op.drop_index('ix_team_stats_team_window', table_name='team_stats')
    op.drop_index(op.f('ix_team_stats_team_name'), table_name='team_stats')
    op.drop_table('team_stats')
    op.drop_index('ix_player_injuries_team_status', table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_team_name'), table_name='player_injuries')
    op.drop_index(op.f('ix_player_injuries_player_name'), table_name='player_injuries')
    op.drop_table('player_injuries')
    # ### end Alembic commands ###
