"""initial_schema

Revision ID: f667f22ad796
Revises: 
Create Date: 2026-03-22 01:11:57.862129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f667f22ad796'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('matches',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('home_team', sa.String(length=255), nullable=False),
    sa.Column('away_team', sa.String(length=255), nullable=False),
    sa.Column('home_score', sa.Integer(), nullable=True),
    sa.Column('away_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_matches_away_team'), 'matches', ['away_team'], unique=False)
    op.create_index(op.f('ix_matches_date'), 'matches', ['date'], unique=False)
    op.create_index('ix_matches_date_home_away', 'matches', ['date', 'home_team', 'away_team'], unique=False)
    op.create_index(op.f('ix_matches_home_team'), 'matches', ['home_team'], unique=False)
    op.create_index(op.f('ix_matches_status'), 'matches', ['status'], unique=False)
    op.create_table('team_ratings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('team_name', sa.String(length=255), nullable=False),
    sa.Column('elo_rating', sa.Float(), nullable=False),
    sa.Column('attack_strength', sa.Float(), nullable=True),
    sa.Column('defense_strength', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_team_ratings_team_name'), 'team_ratings', ['team_name'], unique=True)
    op.create_table('teams',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('current_elo', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_teams_name'), 'teams', ['name'], unique=True)
    op.create_table('odds',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('match_id', sa.String(length=64), nullable=False),
    sa.Column('bookmaker', sa.String(length=100), nullable=False),
    sa.Column('h_odds', sa.Float(), nullable=False),
    sa.Column('d_odds', sa.Float(), nullable=False),
    sa.Column('a_odds', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['match_id'], ['matches.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_odds_bookmaker'), 'odds', ['bookmaker'], unique=False)
    op.create_index('ix_odds_match_bookmaker_time', 'odds', ['match_id', 'bookmaker', 'timestamp'], unique=False)
    op.create_index(op.f('ix_odds_match_id'), 'odds', ['match_id'], unique=False)
    op.create_index(op.f('ix_odds_timestamp'), 'odds', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_odds_timestamp'), table_name='odds')
    op.drop_index(op.f('ix_odds_match_id'), table_name='odds')
    op.drop_index('ix_odds_match_bookmaker_time', table_name='odds')
    op.drop_index(op.f('ix_odds_bookmaker'), table_name='odds')
    op.drop_table('odds')
    op.drop_index(op.f('ix_teams_name'), table_name='teams')
    op.drop_table('teams')
    op.drop_index(op.f('ix_team_ratings_team_name'), table_name='team_ratings')
    op.drop_table('team_ratings')
    op.drop_index(op.f('ix_matches_status'), table_name='matches')
    op.drop_index(op.f('ix_matches_home_team'), table_name='matches')
    op.drop_index('ix_matches_date_home_away', table_name='matches')
    op.drop_index(op.f('ix_matches_date'), table_name='matches')
    op.drop_index(op.f('ix_matches_away_team'), table_name='matches')
    op.drop_table('matches')
    # ### end Alembic commands ###
